Update setup script to start spring-boot app

diff --git a/setup-dev-workspace b/setup-dev-workspace
--- a/setup-dev-workspace
+++ b/setup-dev-workspace
@@ -1,5 +1,24 @@
 #!/usr/bin/env bash
 
+while getopts ":b:h" opt; do
+	case $opt in
+	b)
+		echo -e "\n:: Option selected : Run with backend ::"
+		echo -e "\n== 🚀 Spring boot app will run in the background after DB initialization ==\n"
+		should_start_api=true
+		;;
+	h)
+		echo "Usage: setup-dev-workspace.sh [-b] true"
+		echo "  -b: Start spring-boot backend server"
+		exit 0
+		;;
+	\?)
+		echo "Invalid option: -$OPTARG" >&2
+		exit 1
+		;;
+	esac
+done
+
 should_proceed=true
 
 check_program() {
@@ -52,12 +71,26 @@ if [ -z "$mimock_db" ]; then
 else
 	db_status=$(docker container inspect -f '{{.State.Running}}' $mimock_db)
 	if [ "$db_status" == "false" ]; then
-		echo "🔴 Database is not running"
-		echo "🔵 Re-starting database"
+		echo "🐋 Database is not running"
+		echo "🐳 Re-starting database"
 		docker start $mimock_db >/dev/null
 	else
-		echo "🔵 Mimock database is already running"
+		echo "🐳 Mimock database is already running"
 	fi
+fi
+
+if $should_start_api; then
+	echo -e "\n"
+	echo -e ":: Starting backend server ::\n"
+	cd mimock-backend && nohup ./mvnw spring-boot:run -DskipTests=true -Dapp.profiles=dev >/dev/null 2>&1 &
+	pid=$(echo $!)
+	cd ..
+	echo -e "🔵 Backend server is running\n"
+	echo -e "> To stop the server, run 'kill -9 $pid'\n"
+else
+	echo "⚠️ Spring boot app will not run in the background"
+	echo "🛸 You can run it manually with 'cd ./micmock-backend && ./mvnw spring-boot:run -DskipTests=true -Dapp.profiles=dev'"
+	echo "🛸 You can also run this script with '-b' option to start the app in the background"
 fi
 
 echo -e "\n"
